name: ci_windows

env:
  CMAKE_GENERATOR: Ninja
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"
      - "!scripts/*"


jobs:

  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    strategy:
      matrix:
        shared: [true, false]

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-lapack
          mingw-w64-x86_64-ninja

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3

    - name: config
      run: cmake --preset default -Dparallel:BOOL=false --install-prefix=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: build, test
      run: cmake --workflow --preset default

    - name: install package
      run: cmake --install build

    - name: configure example
      run: cmake -S example -B example/build -Dparallel:BOOL=false -DCMAKE_PREFIX_PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: print config log
      if: ${{ failure() }}
      run: cat example/build/CMakeFiles/CMakeConfigureLog.yaml

    - name: build example
      run: cmake --build example/build

    - name: test example
      run: ctest --test-dir example/build -V
